app/assignments/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, SelectField, TextAreaField,
                    IntegerField, DateField)
from wtforms.validators import DataRequired, NumberRange

class AssignmentForm(FlaskForm):
    due_hour = []
    for hr in range(0, 24):
        if hr == 0:
            due_hour.append((str(hr), "12 a.m."))
        elif hr < 12:
            due_hour.append((str(hr), str(hr) + " a.m."))
        elif hr == 12:
            due_hour.append((str(hr), str(hr) + " p.m."))
        else:
            due_hour.append((str(hr), str(hr-12) + " p.m."))

    due_minute = [(str(min), str(min) + " mins") for min in range(0, 60)]

    title = StringField('Title', validators=[DataRequired()])
    type = SelectField('Type', choices=[('Exam/Quiz', 'Exam/Quiz'),
                                        ('Instructions', 'Instructions'),
                                        ('Lab', 'Lab'),
                                        ('HW', 'HW')])
    content = TextAreaField('Content', validators=[DataRequired()])
    points = IntegerField('Points',
                            validators=[NumberRange(max=500)])
    tries = IntegerField('Tries',
                            validators=[NumberRange(max=10)])

    date_input = DateField('Due Date', format='%Y-%m-%d')
    hour = SelectField('Hour', choices=due_hour)
    minute = SelectField('Minute', choices=due_minute)

app/inbox/forms.py
from flask_wtf import FlaskForm
from wtforms import (StringField, FieldList,
                    HiddenField, TextAreaField,
                    SubmitField)
from wtforms.validators import DataRequired

class NewConversationForm(FlaskForm):
    title = StringField('Conversation Title', validators=[DataRequired()])
    recipients = FieldList(HiddenField('Recipient', validators=[DataRequired()]), min_entries=1)
    message = TextAreaField('Message', validators=[DataRequired()])
    submit = SubmitField('Send')

class NewMessageForm(FlaskForm):
    message = TextAreaField('Message', validators=[DataRequired()])
    submit = SubmitField('Send')

app/deadlines/routes.py
from flask import Blueprint, render_template, url_for
from flask_login import login_required, current_user
from app.models import (Course_User, User_Assignment,
                        Assignment)
from app.filters import autoversion

deadlines_ = Blueprint("deadlines", __name__)

@deadlines_.route('/dashboard/deadlines', methods=['GET'])
@login_required
def deadlines():
    profile_image = url_for('static', filename="profile_images/" + current_user.profile_image)
    courses = Course_User.query.filter_by(user_id=current_user.id).all()
    user_assignments = User_Assignment.query.filter_by(user_id=current_user.id).all()
    user_assignments = [ua.id for ua in user_assignments]
    assignments_due = []
    for course in courses:
        assignments = Assignment.query.filter_by(course_id=course.course_id).order_by(Assignment.duedate_time).all()[::-1]
        for assignment in assignments:
            if assignment.id not in user_assignments:
                assignments_due.append(assignment)

    return render_template("deadlines.html",
                            profile_image=profile_image,
                            assignments=assignments_due,
                            title="Deadlines")

app/home/routes.py
from flask import Blueprint, render_template, url_for, redirect

home_ = Blueprint("home", __name__)

@home_.app_context_processor
def inject_default():
    msg_notif = False
    try:
        profile_image = url_for('static', filename="profile_images/" + current_user.profile_image)
        for convo in current_user.conversations:
            if not convo.read:
                msg_notif = True
                break
    except:
        profile_image = url_for('static', filename="profile_images/default.png")

    return dict(profile_image=profile_image, msg_notif=msg_notif)

@home_.route('/')
@home_.route('/home')
def home():
    return redirect(url_for('users.login'))

@home_.route('/about')
def about():
    return render_template("about.html", title="About")

@home_.route('/packages')
def packages():
    return render_template("packages.html", title="Packages")

from app.filters import autoversion

app/lectures/routes.py
from flask import (Blueprint, request, render_template,
                    redirect, url_for, flash)
from flask_login import login_required, current_user
from app.lectures.forms import NewLectureForm
from app.filters import autoversion
from app.middleware import course_auth, teacher_auth
from app.models import (Course, Lecture)
from app import db
lectures_ = Blueprint("lectures", __name__)

@lectures_.route('/dashboard/courses/<int:course_id>/lectures', methods=['GET', 'POST'])
@login_required
@course_auth
def lectures(course_id):
    profile_image = url_for('static', filename="profile_images/" + current_user.profile_image)
    course = Course.query.filter_by(id=course_id).first()
    lectures = Lecture.query.filter_by(course_id=course_id).all()
    lectures.sort(key=lambda l:l.created_time)

    if request.method == "GET":
        return render_template("lectures.html",
                                profile_image=profile_image,
                                course=course,
                                lectures=lectures,
                                title=f"{course.title} - Lectures")


@lectures_.route('/dashboard/courses/<int:course_id>/lectures/new', methods=['GET', 'POST'])
@login_required
@course_auth
@teacher_auth
def new_lecture(course_id):
    profile_image = url_for('static', filename="profile_images/" + current_user.profile_image)
    course = Course.query.filter_by(id=course_id).first()
    form = NewLectureForm()

    if request.method == "POST" and form.validate_on_submit():
        url = form.url.data
        if "watch?v=" in url:
            url = url.replace("watch?v=", "embed/")
        else:
            url = url.split("/")[-1]
            url = "https://youtube.com/embed/" + url

        lecture = Lecture(course_id=course.id,
                            title=form.title.data,
                            url=url,
                            description=form.description.data)
        db.session.add(lecture)
        db.session.commit()

        flash("Lecture was successfully uploaded.", "success")
        return redirect(url_for("lectures.lectures", course_id=course.id))
    else:
        return render_template("new_lecture.html",
                                profile_image=profile_image,
                                course=course,
                                form=form,
                                title=f"{course.title} - New Lecture",
                                header=" \\ New Lecture")

@lectures_.route('/dashboard/courses/<int:course_id>/lectures/<int:lecture_id>', methods=['GET', 'POST'])
@login_required
@course_auth
def lecture(course_id, lecture_id):
    profile_image = url_for('static', filename="profile_images/" + current_user.profile_image)
    course = Course.query.filter_by(id=course_id).first()
    lecture = Lecture.query.filter_by(id=lecture_id).first()
    teacher = (course.teacher_id == current_user.id)

    if request.method == "GET":
        return render_template("lecture.html",
                                profile_image=profile_image,
                                course=course,
                                lecture=lecture,
                                title=f"{course.title} - Lecture",
                                header=" \\ " + lecture.title)
    elif request.method == "POST" and teacher:
        db.session.delete(lecture)
        db.session.commit()
        flash("You have deleted the lecture.", "success")
        return redirect(url_for("lectures.lectures", course_id=course.id))

app/students/routes.py
from flask import (Blueprint, redirect, url_for, request,
                    render_template, flash)
from flask_login import login_required, current_user
from app.students.utils import (grades_edit_error_handler, calculate_grade,
                                user_grades)
from app.models import (Course, User_Account, Assignment,
                        Course_User, User_Assignment)
from app.filters import autoversion
from app.middleware import course_auth, teacher_auth
from app.assignments.utils import delete_assignment
from app import db
import json

students_ = Blueprint("students", __name__)

@students_.route('/dashboard/courses/<int:course_id>/grades', methods=['GET'])
@login_required
@course_auth
def grades(course_id):
    profile_image = url_for('static', filename="profile_images/" + current_user.profile_image)
    course = Course.query.filter_by(id=course_id).first()
    if current_user.id == course.teacher_id:
        return redirect(url_for("students.students", course_id=course.id))

    (course_user, assignments,
    user_latest_assignments,
    user_points, assignment_points,
    current_assignment_points) = user_grades(course, current_user.id)

    if request.method == "GET":
        return render_template('grades.html',
                                profile_image=profile_image,
                                course=course,
                                course_user=course_user,
                                assignments=assignments,
                                user_latest_assignments=user_latest_assignments,
                                assignment_points=assignment_points,
                                user_points=user_points,
                                current_assignment_points=current_assignment_points,
                                title=course.title + " - Grades")

@students_.route('/dashboard/courses/<int:course_id>/students', methods=['GET', 'POST'])
@login_required
@course_auth
def students(course_id):
    profile_image = url_for('static', filename="profile_images/" + current_user.profile_image)
    course = Course.query.filter_by(id=course_id).first()
    course_students = Course_User.query.filter_by(course_id=course.id).all()
    teacher = User_Account.query.filter_by(id=course.teacher_id).first()
    students_list = []
    drop = request.form.get("drop")

    for student in course_students:
        user = User_Account.query.filter_by(id=student.user_id).first()
        students_list.append(user)

    if request.method == "POST" and drop:
        for course_user in course_students:
            if course_user.user_id == int(drop):
                assignments = Assignment.query.filter_by(course_id=course.id).all()
                for a in assignments:
                    user_assignments = User_Assignment.query.filter_by(user_id=course_user.user_id, assignment_id=a.id).all()
                    for ua in user_assignments:
                        db.session.delete(ua)

                dropped = list(course.dropped)
                dropped.append(drop)
                course.dropped = dropped
                db.session.delete(course_user)

        db.session.commit()
        flash("User has been dropped from course.", "success")
        return redirect(url_for("students.students", course_id=course.id))
    elif request.method == "GET":
        return render_template("students.html",
                                profile_image=profile_image,
                                course=course,
                                course_students=course_students,
                                students_list=students_list,
                                teacher=teacher,
                                title=course.title + " - Students")

@students_.route('/dashboard/courses/<int:course_id>/students/<int:student_id>', methods=['GET'])
@login_required
@course_auth
def student(course_id, student_id):
    course = Course.query.filter_by(id=course_id).first()

    courses_user = Course_User.query.filter_by(user_id=student_id).all()
    assignments_user = User_Assignment.query.filter_by(user_id=student_id).all()

    user = User_Account.query.filter_by(id=student_id).first()

    if current_user.id == user.id:
        return redirect(url_for("profile.profile"))

    profile_image = url_for('static', filename="profile_images/" + user.profile_image)

    if request.method == "GET":
        return render_template("student.html",
                                course=course,
                                user=user,
                                courses_user=courses_user,
                                assignments_user=assignments_user,
                                profile_image=profile_image,
                                title=course.title + " - " + user.first_name + " " + user.last_name)

@students_.route('/dashboard/courses/<int:course_id>/students/<int:student_id>/grades', methods=['GET', 'POST'])
@login_required
@course_auth
@teacher_auth
def student_grades(course_id, student_id):
    profile_image = url_for('static', filename="profile_images/" + current_user.profile_image)
    course = Course.query.filter_by(id=course_id).first()
    student = User_Account.query.filter_by(id=student_id).first()

    (course_user, assignments,
    user_latest_assignments,
    user_points, assignment_points,
    current_assignment_points) = user_grades(course, student_id)

    if request.method == "GET":
        return render_template("grades.html",
                                profile_image=profile_image,
                                course=course,
                                course_user=course_user,
                                assignments=assignments,
                                user_latest_assignments=user_latest_assignments,
                                user_points=user_points,
                                assignment_points=assignment_points,
                                current_assignment_points=current_assignment_points,
                                student=student,
                                title=f"Grades - {student.first_name} {student.last_name}")

@students_.route('/dashboard/courses/<int:course_id>/students/<int:student_id>/grades/edit', methods=['GET', 'POST'])
@login_required
@course_auth
@teacher_auth
def student_grades_edit(course_id, student_id):
    profile_image = url_for('static', filename="profile_images/" + current_user.profile_image)
    course = Course.query.filter_by(id=course_id).first()
    student = User_Account.query.filter_by(id=student_id).first()

    (course_user, assignments,
    user_latest_assignments,
    user_points, assignment_points,
    current_assignment_points) = user_grades(course, student_id)

    request_form = request.form.to_dict()

    if "ajax" in request_form and request.method == "POST":
        return grades_edit_error_handler(request_form, course)
    elif request.method == "POST":
        errors = grades_edit_error_handler(request_form, course)

        # used if user bypasses ajax
        if errors:
            flash("Student grades could not be updated.", "danger")
            return redirect(url_for("students.student_grades", course_id=course.id, student_id=student.id))

        assignments_form = {}
        a_points = 0

        for key, value in request_form.items():
            print(f"{key} : {value}")
            if "assignment_" in key:
                id = key.split("_")
                id = id[1]
                try:
                    assignments_form[id] = int(value)
                except:
                    assignments_form[id] = value

        user_assignments = json.loads(course_user.assignments_done)
        for key, value in assignments_form.items():
            assignment = Assignment.query.filter_by(id=int(key)).first()
            user_assignment = User_Assignment.query.filter_by(user_id=student.id, assignment_id=int(key)).all()

            if user_assignment:
                user_assignment.sort(key=lambda a:a.created_time)

                if value != "-":
                    a_points += assignment.points
                    user_assignment[-1].points = value

                    course_user.points -= user_assignments[key]
                    course_user.points += value

                    user_assignments[key] = value
                else:
                    if assignment.type == "Instructions":
                        for a in user_assignment:
                            delete_assignment(a.filename)

                    course_user.points -= user_assignments[key]

                    del user_assignments[key]

                    # deletes all user_assignments turned in for this assignment
                    for ua in user_assignment:
                        db.session.delete(ua)


            elif value != "-":
                a_points += assignment.points
                user_assignment = User_Assignment(user_id=student_id,
                                                assignment_id=assignment.id,
                                                points=value,
                                                tries=assignment.tries,
                                                type=assignment.type)
                course_user.points += value
                user_assignments[key] = value
                db.session.add(user_assignment)

        course_user.assignments_done = json.dumps(user_assignments)

        Assignment.query

        # grades should be based on assignments they have turned in
        if a_points > 0:
            course_user.grade = '{:.2%}'.format(course_user.points/a_points)
        else:
            course_user.grade = '{:.2%}'.format(0)

        db.session.commit()

        flash(f"Grades for {student.first_name} {student.last_name} have been updated.", "success")
        return redirect(url_for("students.student_grades", course_id=course.id, student_id=student.id))
    elif request.method == "GET":

app/templates/course_layout.html
{% extends "dashboard.html" %}
{% block content_dash %}
  <div class="dashboard-header">
    <div class="d-flex justify-content-center align-items-center">
      <h2>{{ course.id }} {{ course.title }} </h2>
    </div>
  </div>
  {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
          <div class="flash-message-course">
            <div class="alert alert-{{ category }} alert-dismissible fade show text-center" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              {{ message }}
            </div>
          </div>
        {% endfor %}
    {% endif %}
  {% endwith %}
  <div class="d-flex d-md-none justify-content-center">
    <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#courseNavDropdown">
      <span><i class="fas fa-chevron-down"></i></span>
    </button>
  </div>
  <div class="navdrop d-md-none" id="courseNavDropdown">
    <a href="{{ url_for('courses.course', course_id=course.id) }}">About</a>
    <a href="{{ url_for('assignments.assignments', course_id=course.id) }}">Assignments</a>
    <a href="{{ url_for('students.grades', course_id=course.id) }}">Grades</a>
    <a href="{{ url_for('lectures.lectures', course_id=course.id) }}">Lectures</a>
    <a href="{{ url_for('students.students', course_id=course.id) }}">Students</a>
  </div>
  <div class="d-none d-md-flex coursenav pt-2">
    <a href="{{ url_for('courses.course', course_id=course.id) }}">About</a>
    <a href="{{ url_for('assignments.assignments', course_id=course.id) }}">Assignments</a>
    <a href="{{ url_for('students.grades', course_id=course.id) }}">Grades</a>
    <a href="{{ url_for('lectures.lectures', course_id=course.id) }}">Lectures</a>
    <a href="{{ url_for('students.students', course_id=course.id) }}">Students</a>
  </div>
  <script type="text/javascript">
    tinymce.init({
        selector: "textarea",
    });
  </script>
  {% block course_content %}{% endblock course_content %}
{% endblock content_dash %}

app/templates/course_syllabus.html
{% extends "course_layout.html" %}
{% block course_content %}
<div class="dashboard-content mt-2">
  <form class="needs-validation form-group" action="" method="POST" novalidate>
    {{ syllabusform.hidden_tag() }}
    {{ syllabusform.syllabus(class="syllabus-textarea") }}
    <div class="d-flex justify-content-center mt-2 mb-5">
      {{ syllabusform.submit(class="btn btn-blue") }}
    </div>
  </form>
</div>
{% endblock course_content %}

app/templates/dashboard.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="height=device-height, width=device-width, initial-scale=1, shrink-to-fit=no, minimum-scale=1">

    <!-- Bootstrap CSS Framework/CDN -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <!-- <script src="http://code.jquery.com/jquery-1.9.1.js"></script> -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Arimo&display=swap" rel="stylesheet">
    <link href="//cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.css" rel="stylesheet"/>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css')|autoversion }}">

    {{ moment.include_moment(sri=False) }}
    <script src="https://cdn.tiny.cloud/1/5t7si4kzxnjyk0lgsz2gu9mgqhzgjunlvlxfbc1z8u5ircmn/tinymce/5/tinymce.min.js" referrerpolicy="origin"/></script>
    <title>{{ title }}</title>
  </head>
  <body>
    <div>
      <nav>
        <div class="d-flex d-md-none justify-content-between">
          <a class="navbar-brand ml-3" href="{{ url_for('home.home') }}"><i class="fas fa-book"></i> EDUCA</a>
          <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#navDropdown">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="collapse navdrop d-md-none" id="navDropdown">
          <a class="d-flex align-items-center" href="{{ url_for('profile.profile') }}">Profile</a>
          <a href="{{ url_for('courses.courses') }}">Courses</a>
          <a href="#">Deadline</a>
          <a href="#">Inbox</a>
        </div>
        <div class="sidenav">
          <a class="sidenav-brand" href="{{ url_for('home.home') }}">
            <svg height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path class="icons" d="M448 360V24c0-13.3-10.7-24-24-24H96C43 0 0 43 0 96v320c0 53 43 96 96 96h328c13.3 0 24-10.7 24-24v-16c0-7.5-3.5-14.3-8.9-18.7-4.2-15.4-4.2-59.3 0-74.7 5.4-4.3 8.9-11.1 8.9-18.6zM128 134c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm0 64c0-3.3 2.7-6 6-6h212c3.3 0 6 2.7 6 6v20c0 3.3-2.7 6-6 6H134c-3.3 0-6-2.7-6-6v-20zm253.4 250H96c-17.7 0-32-14.3-32-32 0-17.6 14.4-32 32-32h285.4c-1.9 17.1-1.9 46.9 0 64z"/></svg>
            <span class="sidenav-text">EDUCA</span>
          </a>
          <a class="sidenav-item" href="{{ url_for('profile.profile') }}">
            <!-- <svg height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="icons" d="M256 288c79.5 0 144-64.5 144-144S335.5 0 256 0 112 64.5 112 144s64.5 144 144 144zm128 32h-55.1c-22.2 10.2-46.9 16-72.9 16s-50.6-5.8-72.9-16H128C57.3 320 0 377.3 0 448v16c0 26.5 21.5 48 48 48h416c26.5 0 48-21.5 48-48v-16c0-70.7-57.3-128-128-128z"/></svg> -->
            <div class="profile-img-sidenav" style="background-image: url({{ profile_image }});"></div>
            <span class="sidenav-text">Profile</span>
          </a>
          <a class="sidenav-item" href="{{ url_for('courses.courses') }}">
            <svg height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path class="icons" d="M497.9 142.1l-46.1 46.1c-4.7 4.7-12.3 4.7-17 0l-111-111c-4.7-4.7-4.7-12.3 0-17l46.1-46.1c18.7-18.7 49.1-18.7 67.9 0l60.1 60.1c18.8 18.7 18.8 49.1 0 67.9zM284.2 99.8L21.6 362.4.4 483.9c-2.9 16.4 11.4 30.6 27.8 27.8l121.5-21.3 262.6-262.6c4.7-4.7 4.7-12.3 0-17l-111-111c-4.8-4.7-12.4-4.7-17.1 0zM124.1 339.9c-5.5-5.5-5.5-14.3 0-19.8l154-154c5.5-5.5 14.3-5.5 19.8 0s5.5 14.3 0 19.8l-154 154c-5.5 5.5-14.3 5.5-19.8 0zM88 424h48v36.3l-64.5 11.3-31.1-31.1L51.7 376H88v48z"/></svg>
            <span class="sidenav-text">Courses</span>
          </a>
          <a class="sidenav-item" href="{{ url_for('deadlines.deadlines') }}">
            <svg height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path class="icons" d="M148 288h-40c-6.6 0-12-5.4-12-12v-40c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v40c0 6.6-5.4 12-12 12zm108-12v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 96v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm-96 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm192 0v-40c0-6.6-5.4-12-12-12h-40c-6.6 0-12 5.4-12 12v40c0 6.6 5.4 12 12 12h40c6.6 0 12-5.4 12-12zm96-260v352c0 26.5-21.5 48-48 48H48c-26.5 0-48-21.5-48-48V112c0-26.5 21.5-48 48-48h48V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h128V12c0-6.6 5.4-12 12-12h40c6.6 0 12 5.4 12 12v52h48c26.5 0 48 21.5 48 48zm-48 346V160H48v298c0 3.3 2.7 6 6 6h340c3.3 0 6-2.7 6-6z"/></svg>
            <span class="sidenav-text">Deadlines</span>
          </a>
          <a class="sidenav-item" href="{{ url_for('inbox.inbox') }}">
            <svg height="1em" width="1em" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 576 512"><path class="icons" d="M567.938 243.908L462.25 85.374A48.003 48.003 0 0 0 422.311 64H153.689a48 48 0 0 0-39.938 21.374L8.062 243.908A47.994 47.994 0 0 0 0 270.533V400c0 26.51 21.49 48 48 48h480c26.51 0 48-21.49 48-48V270.533a47.994 47.994 0 0 0-8.062-26.625zM162.252 128h251.497l85.333 128H376l-32 64H232l-32-64H76.918l85.334-128z"/></svg>
            <span class="sidenav-text">Inbox</span>
            {% if msg_notif %}
              <span id="new-msg-notif">
              </span>
            {% endif %}
          </a>
        </div>
      </nav>
      <!-- <div class="container col-12 col-md-11 p-0"> -->
      <div class="ml-md-5">
        {% block content_dash %}{% endblock %}
      </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  
    <script src="//cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>

    <script type="text/javascript" src="{{ url_for('static', filename='js/dashboard.js')|autoversion }}"></script>
  </body>
</html>

app/templates/home.html
{% extends "layout.html" %}
{% block content %}
<!-- Top Section -->
<section>
  <div class="d-flex flex-column flex-md-row align-items-center justify-content-center p-0 m-0">
  </div>
</section>
<!-- Middle Section -->
{% endblock content %}

app/templates/verify_email.html
{% extends "layout.html" %}
{% block content %}
    <div class="token-container">
        <div class="token-card text-center shadow-sm">
            <p class="">An email has been sent to <span class="blue-text">{{ email }}</span>, please check it to confirm your account.</p>
            <p class="m-0">Click <a class="fancy-link" href="{{ url_for('users.resend_email_message', email=email) }}">here</a> to resend the confirmation link.</p>
        </div>
    </div>
{% endblock content %}